sudo: required
services:
- docker
language: python
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- docker-compose -f docker-compose.dev.yml up --build -d
- docker build -t battleground/battleground .
- docker run --network=host battleground/battleground python battleground/utils/start.py
script: docker run --network=host battleground/battleground pytest unit_tests
after_success:
- chmod +x ./deploy_scripts/*.sh
- test $TRAVIS_BRANCH = "master" &&
  test $TRAVIS_PULL_REQUEST = "false" &&
  ./deploy_scripts/do_deploy.sh
