sudo: required
services:
  - docker
language: node_js
node_js:
  - "7"
install:
  - cd ui/frontend
  - npm install
  - npm run build
  - cd ../..
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - docker-compose -f docker-compose-ui.yml up --build -d
  - docker build -t main .
  - docker run --network=host main python start.py
script: docker run --network=host main pytest unit_tests
