sudo: required
services:
- docker
language: node_js
node_js:
- '7'
install:
- cd ui/frontend
- npm install
- npm run build
- cd ../..
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- docker-compose -f docker-compose-ui.yml -f docker-compose.prod.yml up --build -d
- docker build -t battleground/battleground .
- docker run --network=host battleground/battleground python start.py
script: docker run --network=host battleground/battleground pytest unit_tests
after_script:
  - chmod +x ./deploy_scripts/*.sh
  - ./deploy_scripts/push_images.sh
env:
  global:
  - secure: vgBfw0UiYND6rhu3cKK4LgTeiizDS+VaU8Vq5lmGzezZPqAlvmQbd0Olr6Ls4P3LB6uvroINIsSiA9pjk6YhqQkwHvnubmF6WX4X4Hk74SyaRpHLoQxVpC3/uyINwF1oA0cywrmPyPsyP/E6APLbfCcv7zkUs1MX6EbWlg3XIyKvK56QRbZ2shu2KKDtTPV0PbQDC3Fy1mSEx33BZFMJcvj1xcWc/qJdYwPvcjLRGldfAPArsRdswLg0ch/AbmZJcvHDva5RfNBGWsQz3LuGcdC7fv2UipyK+r8uRl86rlBk0c1LcowFD0a16tGKU+aB8HUcF7GrXAPNA9HP1Pd/q9rxaaQZX3Q+9M+5i0dEEKXQjKUBMKgmSk3xgQdkfGYcggR7gidtYwgfd3JTmaxwBHlcSQspeO/oAQrcb65ZlmLonA8XJXMuagmMpdHt9t32wxwCYAnmP+HgOcEJpO6bjDfcqOAGbthAoKYvJIdhTWuOmTvikS6DS2wg/MgkSm69cDyT6h8ai4hxYSz3H+LpiyFD8QtxxGPBz9HRkTXPIPIZ1F2lWpcGx5efT2dfWSUZdAgChvSFjw87uBrXQTE3B/e7Yh7FRjTnVGQQo6fFd0vteReUuspOIbT0+DycS7oGZHDuNKuwSIN698LvVHe0b67mVjR7IGttSPHtPUZt+js=
  - secure: vXmDH+WznGd5RcQ5FTw9LMmGzrlyP5USwkdYyg96uQ5o7Zj2AIbEr2ycIDjhrPC3kWmXftFfJtx39RQ/u3enAJqpo/7+qFbVkT2jLvFv98ndrDuFBdZM0eRQn4RkZLQb7db2KvrP6hN05j+SZB/zQZFXztiTlbE0CPXsD86gKsZPlodeP+Cfp4z1Y+9dGKVgLi3XeTTojoRiaOdUqMh25tAVTlGdREXaI5RCEsVb0yAUiCpUOndqTo75Wf7sNQdlxeZzzm7su1Fyz1DEVu27Xh3Mewj+ljJNsoEU6kIO/mpRbVXLA7gsO2fVBBztP0LJQZMJFNnCp0EjJ15c1K/1s9WrSzKtWGMhatugnJk/TDnO5DCqvJdUOWMkVFBISRcCf2a7mwZqYZDwae8QhqE4pPMpnb84k5ewlOUMQC4igFpIVf+c5LkRJMLg2cwjYCP7OViKy278NsqpbVjaiamvUgmO97qHFWnqbBXyDQziVEj3+4/KM3zuMmrYepp8BMTECfKPdb6yBYAxbpT8BTg+k2UB+2fRyxvQFhAWjO+pRtw6HmAvQNMcY4qxQ2j9ZsNJxNwKK/eJ0EsIWGpCIhkBt/DZRzxAUYuC0w7d4ZgVl2NHiPV8LCT309doVwmC0KOFx+vYInIIwYx9f/5qbp6anbgXUb2jxk20Pv/zlRFyHnk=
