version: '2'

services:
  mongo:
    image: mongo:3.4
    volumes:
      - /data:/data/db
    ports:
      - 27017:27017

  uwsgi:
    image: battleground/uwsgi:latest
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo:27017

  nginx:
    image: battleground/nginx:latest
    depends_on:
      - uwsgi
    ports:
      - 80:80

  battleground:
    image: battleground/battleground:latest
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo:27017
