version: '3'

services:

  nginx:
    build: ./ui/frontend
    ports:
      - 80:80

  battleground:
    image: battleground/battleground:latest
    build: .
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
