version: '3'

services:
  couchdb:
    image: couchdb:1.6
    volumes:
      - /data:/usr/local/var/lib/couchdb
    ports:
      - 5984:5984

  uwsgi:
    image: uwsgi:latest
    build:
      context: .
      dockerfile: ui/api/Dockerfile
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
    # volumes:
    #   - ./backend/public:/usr/src/app/public

  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uwsgi
    ports:
      - 8888:80
