version: '3'

services:

  nginx:
    image: battleground/nginx:latest
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80

  battleground:
    image: battleground/battleground:latest
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo:27017
