version: '3'

services:
  couchdb:
    image: couchdb:1.6
    volumes:
      - /data:/usr/local/var/lib/couchdb
    ports:
      - 5984:5984

  uwsgi:
    image: uwsgi:latest
    build: ui/api
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984

  nginx:
    build: ./ui/frontend
    depends_on:
      - uwsgi
    ports:
      - 8888:80
